# -*- coding: utf-8 -*-
"""least_squares_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UBK6sFvnYi9ZNgnT9oGXoeAChrwgnUU4
"""

def least_squares_regression(x, y):
    """
    Compute the least squares regression line for given x and y values.
    Displays the equation in LaTeX format and returns the coefficients.

    Author: Edward Pineda-Castro
    """
    from IPython.display import display, Math

    # Calculate the necessary sums
    n = len(x)
    sum_x = sum(x)
    sum_y = sum(y)
    sum_xy = sum(x[i]*y[i] for i in range(n))
    sum_x_squared = sum(xi ** 2 for xi in x)

    # Calculate the slope (b1) using the formula
    b1 = (n * sum_xy - sum_x * sum_y) / (n * sum_x_squared - sum_x ** 2)

    # Calculate the intercept (b0) using the formula
    b0 = (sum_y - b1 * sum_x) / n


    # Display the regression equation in LaTeX-style format
    display(Math(f"\\hat{{y}} = {b0:.2f} + {b1:.2f}x"))
    print("\n")
    print("Professor: Edward Pineda-Castro")
    print("Department of Mathematics")
    print("Los Angeles City College")

    return b0, b1